package com.keyin.IslandSerenity;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import com.keyin.Users.User;
import com.keyin.Users.UserRepository;
import com.keyin.Activities.Activity;
import com.keyin.Activities.ActivityRepository;
import com.keyin.Rooms.Room;
import com.keyin.Rooms.RoomRepository;
import com.keyin.Reviews.Review;
import com.keyin.Reviews.ReviewRepository;

@SpringBootApplication
public class IslandSerenity {

    public static void main(String[] args) {
        SpringApplication.run(IslandSerenity.class, args);
    }

    @Bean
    CommandLineRunner initDatabase(UserRepository userRepository, RoomRepository roomRepository, ActivityRepository activityRepository, ReviewRepository reviewRepository) {
        return args -> {
            // Initialize Users
            userRepository.save(new User("user1", "Password1!"));
            userRepository.save(new User("user2", "Password2!"));
            userRepository.save(new User("user3", "Password3!"));

            // Initialize Rooms
            roomRepository.save(new Room(101, "Beachfront Swim-Up Suite", "Oceanfront", "Suite", "1 King", 3, "Indulge in breathtaking oceanfront views from this exquisite beachfront swim-up suite. Revel in the luxury of a private balcony, an elegant separate shower, a sumptuous king bed, and a plush sofa, all designed to enhance your coastal escape.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-oceanfront-junior-suite-swim-up-king-room.jpg/a960c533ec670132e78d2f3c022f1a43", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-oceanfront-junior-suite-swim-up-king-view-1.jpg/9751fde1af8bd8e515051a97e74e1b07", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-junior-suite-swim-up-king-bathroom-1.jpg/8026a666ecf7e95843ee98d52a688c8d"));
            roomRepository.save(new Room(102, "Oceanfront Terrace Family Suite", "Oceanfront", "Suite", "1 King, 2 Twins, 1 Sofa Bed", 6, "The Oceanfront Terrace Suite is on ground level, emerging from your spacious suite you will be directly on the beach which for children eager to participate in our many water activities will be a huge bonus! The master bedroom boasts a king-size bed and the second bedroom has twin beds. Outdoor living is also provided for with a terrace, day beds and dining area for the family to get together and still never miss a moment of glorious sunshine.", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Terrace-Suite-Living-Area.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Terrace.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Terrace-View.jpg"));
            roomRepository.save(new Room(103, "Tropical Garden Swim-Up Suite w/ Jacuzzi", "Tropical Garden", "Suite", "1 King", 3, "Our luxurious ground-floor Garden Swim-Up King Suite is designed to provide an unparalleled experience. It is equipped with a sumptuous king-size bed and features an indoor jacuzzi for ultimate relaxation. Additionally, guests can enjoy the privacy of a secluded garden with direct access to the pool, creating a perfect blend of comfort and convenience.", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-one-bedroom-suite-jacuzzi/elegelegance-club-one-bedroom-suite-jacuzzi1-majestic-elegance-punta-cana.jpg", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-one-bedroom-suite-jacuzzi/elegelegance-club-one-bedroom-suite-jacuzzi4-majestic-elegance-punta-cana.jpg", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-one-bedroom-suite-jacuzzi/elegelegance-club-one-bedroom-suite-jacuzzi3-majestic-elegance-punta-cana.jpg"));
            roomRepository.save(new Room(104, "Ocean Breeze Room", "Oceanfront", "Room", "1 King", 3, "The Oceanfront King Room offers a generously sized and elegantly appointed sitting area, providing an exquisite retreat for guests. With its spacious layout and French doors that open directly onto the beach, this room is ideal for those seeking to luxuriate in the sun or explore the lively surroundings. It combines ultimate comfort with the allure of adventure, ensuring a perfect blend of relaxation and excitement.", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-Breeze-Superior-Room1.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-Breeze-Superior-Room2.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-Breeze-Superior-Room8.jpg"));
            roomRepository.save(new Room(201, "Garden Suite w/ Private Pool", "Tropical Garden", "Suite", "1 King", 3, "Experience the ultimate in relaxation and luxury with the Garden Suite.The suite features an open, airy layout that seamlessly connects to a lush outdoor space, where you can enjoy a refreshing dip in your own private pool, and relax in a king bed. With elegant decor and serene garden views, this suite provides a tranquil retreat for rejuvenation and peaceful escape. Ideal for couples seeking both comfort and exclusivity, the Garden Suite promises an unforgettable stay amidst natures beauty.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-one-bedroom-master-swim-up-suite-room.jpg/eae81229981f7a3230e20831ec349497", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-one-bedroom-master-swim-up-suite-view.jpg/5647754643b1512738a01469a436e6d5", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-one-bedroom-master-swim-up-suite-bathroom-1.jpg/0948733f8eddecb10e2da060c8e4e0d0"));
            roomRepository.save(new Room(202, "Seaside Serenity Room", "Ocean", "Room", "1 King", 2, "The Ocean View King Room is a chic, open-concept studio that showcases panoramic ocean vistas through expansive windows. Designed for both relaxation and luxury, this room serves as the perfect vantage point to enjoy breathtaking sunsets. Its elegant layout and stunning views create an idyllic setting for a memorable escape, making it an ideal choice for those seeking both comfort and natural beauty.", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-View-Superior-Room.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-View-Superior-Room5.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-View-Superior-Room3.jpg"));
            roomRepository.save(new Room(203, " Tranquility Queen Suite w/ Balcony", "Ocean", "Suite", "2 Queens", 4, "The Ocean View Two Queen Suite offers a serene retreat with stunning ocean views from its private balcony. This suite features two plush queen beds, a separate shower for added convenience, and a comfortable sofa, creating a perfect blend of style and comfort for a relaxing stay.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-club-ocean-view-junior-suite-double-room.jpg/bb86c7a77baafb6ec685465c3df7f1ad", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-junior-suite-partial-view-balcony-web.jpg/900b979b507c1107eae66ba0ab075009", "https://resolve.sandals.com/sri?set=key[resolve.pixelRatio],value[1.25]&set=key[resolve.width],value[1500]&set=key[resolve.height],value[10000]&set=key[resolve.imageFit],value[containerwidth]&set=key[resolve.allowImageUpscaling],value[0]&set=key[resolve.format],value[webp]&set=fileName[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fslu%2Faccommodations%2Flarge%2Fslu-120.jpg]&source=continueonerror[true],name[image],url[global.fileName]&set=prdImageFound[global.source.success]&source=if[(!%20global.source.success)],name[base1],url[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fglobal%2Fcoming-soon%2Fbackground.jpg]&scale=options[limit],size[1500x10000]&sink=format[webp],if[(%20prdImageFound%20)],quality[70]"));
            roomRepository.save(new Room(204, "Enchanted Secret Garden Room", "Tropical Garden", "Room", "1 King", 3, "The Garden View King Room is a cozy, inviting space designed for comfort and relaxation. Featuring a plush king bed and a tranquil garden view, this room offers a peaceful retreat perfect for unwinding and enjoying the natural beauty that surrounds you.", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/375053570.jpg?k=1d9ac0f89adabec9734e56462f223268df764c1b709bda1221efb94f6938b8d8&o=&hp=1", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/375053578.jpg?k=90a1b02b15e57c739378306365b1fddbeec7d01d059000f9292d6b92dd08d6fc&o=&hp=1", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/375053548.jpg?k=05f8c8d0151c964a4edab63fa13d219f1e49181de26062279d7c1349ac8e8bdc&o=&hp=1"));
            roomRepository.save(new Room(301, "Horizon Haven Suite w/ Balcony", "Ocean", "Suite", "1 King, 2 Twins, 1 Sofa Bed", 6, "Located on the family-dedicated area of the resort, the upper level Ocean View Family Suite has the advantage of two separate bedrooms and a balcony off the master bedroom with beach views. Comfort and style are reflected in the bright, tasteful décor and furnishings and all the extra touches you would expect are included. You can be assured that your family will be thrilled with their stay here.", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-junior-suite-jacuzzi/elegance-club-junior-suite-jacuzzi1-majestic-elegance-punta-cana.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/CB_Bay_Suite_2_1.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Balcony-Twin-Room.jpg"));
            roomRepository.save(new Room(302, "Serenity Suite w/ Terrace", "Ocean", "Suite", "2 King, 2 Twins, 1 Sofa Bed", 8, "The Serenity Suite is the ultimate choice for resort accommodation. Spacious, sun-filled and magnificently appointed it is ideal for sharing with other couples or for small family groups. The oceanfront terraces are large with uninterrupted views which are all your own. They have two king-size bedded rooms and one twin bedded room, all ensuite. It also features a large sitting room area extending onto the L-shaped terrace giving you those uninterrupted views in every direction.", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Carlisle-Suite.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Carlisle-Suite-Bathroom.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/CB_Beach_Balcony_Suite_-_Balcony.JPG"));
            roomRepository.save(new Room(303, "Honeymoon Bliss Suite w/ Balcony", "Ocean", "Suite", "1 California King", 3, "The Ocean View California King Honeymoon Suite is a luxurious sanctuary offering unparalleled elegance and comfort. Featuring expansive ocean views from every window, this suite includes a grand california king-sized bed, a lavish living area, and a sophisticated dining space. The suite also boasts a private balcony, perfect for enjoying breathtaking sunsets, and a sumptuous bathroom with premium amenities. With its refined décor and spacious layout, this suite ensures a truly opulent experience.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-presidential-suite-room-web1.jpg/47c35ae690c8524db91fc3ce7fe01c3e", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-presidential-suite-living-dining-room-butler-web1.jpg/783e7fe4318700164b11dd026d2a323b", "https://resolve.sandals.com/sri?set=key[resolve.pixelRatio],value[1.25]&set=key[resolve.width],value[1500]&set=key[resolve.height],value[10000]&set=key[resolve.imageFit],value[containerwidth]&set=key[resolve.allowImageUpscaling],value[0]&set=key[resolve.format],value[webp]&set=fileName[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fslu%2Faccommodations%2Flarge%2Fslu-045.jpg]&source=continueonerror[true],name[image],url[global.fileName]&set=prdImageFound[global.source.success]&source=if[(!%20global.source.success)],name[base1],url[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fglobal%2Fcoming-soon%2Fbackground.jpg]&scale=options[limit],size[1500x10000]&sink=format[webp],if[(%20prdImageFound%20)],quality[70]"));
            roomRepository.save(new Room(401, "Skyline Luxe Penthouse Suite w/ Hot Tub & Balcony", "Ocean", "Suite", "1 California King, 2 Queens, 1 sofa bed", 8, "The Ocean View California King Penthouse Suite is a spacious, private apartment-style suite with separate living space, perfect for families or groups. Located on the top floor and accommodates up to 8 guests with 2 bedrooms, 3 full bathrooms, and a sleeping arrangement that includes a california king-sized bed, two queen-sized beds, and a full sofa bed. Enjoy a covered balcony with a private hot tub.", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Playitas-Suite.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Playitas-Suite18.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Playitas-Suite6.jpg"));
            roomRepository.save(new Room(1, "Rainforest Retreat Villa", "Rainforest", "Villa", "1 California King", 3, "Embrace the essence of island paradise in the Rainforest Suite, where the vibrant rainforest and tranquil ocean come together. This luxurious suite features an open-plan design that seamlessly blends with the lush tropical surroundings, creating a serene and inviting atmosphere. Guests will enjoy a restful night in a plush king-size bed, waking to the soothing sounds of the ocean, mixed with the unique soundtrack of the rainforest and breathtaking views of the island. The suite's gentle blend of forest fragrances and ocean breezes promises to rejuvenate both body and mind, offering an unparalleled tropical escape for two adults.", "https://www.greengetaways.com.au/wp-content/uploads/2017/12/Crystal-Creek-lodges_cedar_wide_evening.jpg", "https://www.greengetaways.com.au/wp-content/uploads/2017/12/Crystal-Creek-deck_wide.jpg", "https://www.greengetaways.com.au/wp-content/uploads/2017/12/Crystal-Creek-lodges_numinbah_bed_bath_view.jpg"));
            roomRepository.save(new Room(2, "Ocean Top Villa", "Oceanfront", "Villa", "1 California King", 3, "Elevate your escape with the Ocean Top Villa, a premier retreat perched above the azure waves. This exquisite villa offers uninterrupted ocean views and the ultimate in luxury with a private infinity pool and an indulgent jacuzzi. The open-plan design seamlessly integrates indoor and outdoor spaces, allowing you to fully immerse yourself in the stunning seascape. Relax on your private terrace, take a dip in the infinity pool, or unwind in the jacuzzi while gazing out over the horizon.", "https://cache.marriott.com/is/image/marriotts7prod/mlera-bedroom-ocean-1150:Wide-Hor?wid=1336&fit=constrain", "https://cache.marriott.com/content/dam/marriott-renditions/MLERA/mlera-ocean-villa-3568-hor-wide.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=1336px:*", "https://cache.marriott.com/content/dam/marriott-renditions/MLERA/mlera-villa-bathroom-3557-hor-wide.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=1336px:*"));
            roomRepository.save(new Room(3, "Beachfront Villa w/ Private Beach & Pool", "Beachfront", "Villa", "1 King", 3, "Indulge in the ultimate coastal luxury with the Beachfront Villa, where your private paradise awaits. This exceptional villa offers exclusive access to a pristine private beach and a stunning pool, seamlessly blending the beauty of the shoreline with sophisticated comfort. Step directly from your villa onto soft, sandy shores, or relax in your private pool while soaking in panoramic ocean views. Designed for the discerning traveler, the Beachfront Villa provides an unparalleled setting for relaxation and indulgence, making every moment of your stay a serene and memorable experience.", "https://worldvillas.eu/img/641x336/8492.jpg", "https://worldvillas.eu/img/641x336/8492/7defd00746891b554c6f4be2907467f4.jpg", "https://worldvillas.eu/img/641x336/8492/491398f7c06408285de09cf7d9c8f29f.jpg"));
            roomRepository.save(new Room(4, "Family Beachfront Villa w/ Pool", "Beachfront", "Villa", "1 Queen, 2 Twin, 1 Daybed", 5, "Create unforgettable memories with your loved ones in the Family Beachfront Villa. This spacious and inviting villa offers direct access to a beautiful sandy beach, perfect for family fun and relaxation. Enjoy quality time together in the large, private pool or explore the nearby shoreline. Designed with comfort and convenience in mind, the villa features ample living space, modern amenities, and stunning ocean views, ensuring a memorable and enjoyable stay for families of all sizes. The Family Beachfront Villa is your ideal coastal retreat for bonding and making the most of every sun-drenched day.", "https://maldives-magazine.com/pictures/constance-halaveli-family-beach-pool-villa.jpg", "https://maldives-magazine.com/pictures/constance-halaveli-family-beach-pool-villa-bedroom.jpg", "https://maldives-magazine.com/pictures/constance-halaveli-family-beach-pool-villa-bedroom-5.jpg"));
            roomRepository.save(new Room(5, "Sky Nest Treehouse", "Rainforest", "Villa", "2 King, 2 Twin, 1 Sofa Bed", 8, "Experience luxury tree-top living in this 4,000 square-foot villa nestled in the rainforest. Combining eco-friendly design with striking architecture, the villa features contemporary interiors, a sleek kitchen with a marble island, and a beautiful stone hot tub. Upstairs, 3 bedrooms offer ensuite bathrooms, luxury linens, flat-screen TVs, and Mexican-inspired decor, all opening to a wrap-around terrace for al fresco lounging. With access to nearby beach clubs, hiking and biking trails, and included amenities like daily housekeeping and 24/7 security, this villa promises an unforgettable tropical retreat.", "https://gallery.streamlinevrs.com/units-gallery/00/05/4F/image_164231367.jpeg", "https://gallery.streamlinevrs.com/units-gallery/00/05/4F/image_164231384.jpeg", "https://gallery.streamlinevrs.com/units-gallery/00/05/4F/image_164231379.jpeg"));


            // Initialize Activities
            activityRepository.save(new Activity('Snorkel Safari: Explore the Underwater Wonderland!', 'Dive into the vibrant underwater world with our snorkeling excursions! Explore crystal-clear waters teeming with colorful coral reefs and exotic marine life. Whether you\'re a seasoned snorkeler or a first-timer, our guided tours provide all the equipment and safety instructions you need for an unforgettable experience. Swim alongside tropical fish, discover hidden coves, and enjoy the serene beauty of the ocean. Perfect for families, couples, and solo adventurers, snorkeling at our resort offers a glimpse into the magical aquatic life that awaits just beneath the surface.', 10, '10:00 AM', 'https://cdn2.picryl.com/photo/2015/01/01/snorkeling-at-the-park-dry-tortugas-national-park-2015-a6c664-1024.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLnyB8cerN9IgK6WSWTAFJGSEgq0SYhgvirA&s', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRqrMhObe1tLovvV55uqfePqtC4fAYGpe5VA&s'));
            activityRepository.save(new Activity('Sea Cave Exploration', 'Embark on an exhilarating journey into the mysterious sea caves along our coastline. Paddle through hidden passages and marvel at the stunning rock formations carved by nature over centuries. This guided tour offers a unique perspective of the ocean\'s beauty from sea kayaks, allowing you to discover secret coves, natural arches, and fascinating marine life. Perfect for adventure seekers and nature lovers alike, our Sea Cave Exploration promises an unforgettable experience of wonder and discovery.', 6, '10:00 AM', 'https://live.staticflickr.com/65535/49524568222_590dcd99a7_b.jpg', 'https://live.staticflickr.com/4862/31967307358_8831d547be_b.jpg', 'https://i2.pickpik.com/photos/735/44/970/cave-sea-blue-caves-greece-preview.jpg'));
            activityRepository.save(new Activity('Tropical Waterfall Oasis Excursion', 'Escape to a serene tropical paradise with our Tropical Waterfall Oasis excursion. Immerse yourself in the lush surroundings as you trek through vibrant rainforests to discover a stunning waterfall. Swim in the crystal-clear pools, relax under the cascading waters, and soak in the natural beauty of this hidden gem. This peaceful retreat is perfect for those seeking tranquility and a connection with nature, offering a refreshing and rejuvenating experience in the heart of the tropics.', 15, '10:00 AM', 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvdXB3azYxNzMwMDMyLXdpa2ltZWRpYS1pbWFnZS1rb3dyMjZxei5qcGc.jpg', 'https://freerangestock.com/sample/160607/lush-waterfall-in-a-green-forested-area.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaFjv11ojdSDcRhUVF9yVEU7z2Ne2oST5m1Q&s'));
            activityRepository.save(new Activity('Bazaar Buzz: Local Market Adventure', 'Discover the vibrant culture and unique treasures of the local area with our Local Shopping Excursion. Stroll through bustling markets and charming boutiques, where you\'ll find handcrafted souvenirs, exquisite jewelry, and traditional crafts. Engage with local artisans, sample regional delicacies, and soak in the lively atmosphere. This excursion offers a delightful way to take home a piece of the local flavor and create lasting memories of your stay.', 10, '10:00 AM', 'https://www.ncl.com/sites/default/files/FNC_64_1920%20X%201080%20XL.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZkC6nSk3yaxDPXpLEKYpCCFbeGSS19PGaOA&s'));
            activityRepository.save(new Activity('Sunset Cruise', 'As the vibrant sun dips down into the horizon, set sail with your special someone on a romantic sunset cruise. Out on the ocean, you’ll become immersed in the sunset’s vibrant colors which will glimmer and reflect on the water around you. There is truly no better way to enjoy the final hours of a day on your romantic tropical vacation.', 8, '4:00 PM', 'https://img.freepik.com/free-photo/architecture-lake-chinese-architecture-city-scenic_1417-357.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid', 'https://img.freepik.com/free-photo/beautiful-ocean-with-small-boat-floating-water-sunset_181624-3738.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid', 'https://img.freepik.com/free-photo/happy-young-couple-love-smiling-enjoying-boat-trip-sea-romance-vacation-concept-boyfriend-tenderly-touches-her-cheek-girlfriend-feels-butterflies-stomach_176420-15399.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid'));
            activityRepository.save(new Activity('Tropical Garden Picnic for Two', 'Experience an intimate escape in paradise with our Tropical Garden Picnic for Two. Nestled in a lush, vibrant garden, this exclusive picnic features a charming setup under a canopy of swaying palms and colorful flowers. Enjoy a gourmet selection of fresh, tropical delicacies—juicy fruits, artisanal cheeses, and handcrafted pastries—paired with a bottle of chilled champagne or tropical mocktails. The serene ambiance is enhanced by soft, island-inspired music and the gentle breeze, making it the perfect setting for a romantic and unforgettable dining experience.', 2, '11:00 AM', 'https://img.freepik.com/free-photo/woman-sitting-holding-glass-champagne-traditional-fruits-croissants-cheese_291049-190.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid', 'https://www.freepik.com/free-photo/two-glasses-champagne-bottle-picnic-basket-beach-blanket_991226.htm#fromView=search&page=1&position=2&uuid=b96becc7-28d0-4315-8340-706dfb583863', 'https://img.freepik.com/free-photo/summer-picnic-with-plate-tropical-fruits_169016-1674.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid'));
            activityRepository.save(new Activity('Beach Bonfire', 'Gather around a crackling beach bonfire for a magical evening under the stars. Set against a backdrop of the gentle waves and moonlit sands, this cozy bonfire event invites you to relax with friends or loved ones. Enjoy toasted marshmallows, s\'mores, and warm drinks while sharing stories and creating memories. The rhythmic sound of the ocean and the glow of the fire create an enchanting atmosphere, making it an ideal setting for a memorable seaside night.', 15, '8:00 PM', 'https://img.freepik.com/free-photo/full-shot-friends-sitting-together_23-2149183729.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid', 'https://img.freepik.com/free-photo/high-angle-chairs-around-bonfire_23-2149445621.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid', 'https://img.freepik.com/free-photo/full-shot-happy-senior-friends-night_23-2149213415.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid'));
            activityRepository.save(new Activity('Oceanfront Serenity: Beach Yoga Session', 'Embrace tranquility with a Beach Yoga Session, where the serene sounds of the ocean and the soft sand beneath your feet enhance your practice. Join our guided session as the sun rises or sets, allowing the natural beauty of the beach to rejuvenate your mind and body. With each stretch and pose, you\'ll find harmony in the rhythmic waves and gentle breeze, creating a peaceful and invigorating experience. Ideal for all levels, this session offers a unique blend of relaxation and fitness in an idyllic coastal setting.', 10, '6:00 AM', 'https://img.freepik.com/free-photo/full-shot-people-stretching-near-lake_23-2148262490.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid', 'https://img.freepik.com/free-photo/full-shot-man-doing-yoga-beach_23-2150170348.jpg?uid=R106210913&ga=GA1.1.75415720.1720630919&semt=ais_hybrid', 'https://img.freepik.com/free-photo/full-shot-women-exercising-yoga-mat-beach_23-2149386477.jpg?t=st=1722473454~exp=1722477054~hmac=9bb74982bf387d39cf22cf372b8bad4f13df21818d8109ad3ea5616665f1d257&w=996'));
            activityRepository.save(new Activity('Tropical Spa Retreat', 'Escape to a world of tranquility with our Tropical Spa Retreat. This luxurious sanctuary offers a serene blend of natural beauty and sophisticated comfort, designed to rejuvenate both body and mind. Nestled in a lush tropical setting, the retreat features spacious accommodations with elegant furnishings and panoramic views of verdant landscapes. Enjoy indulgent spa treatments in your private oasis, complete with a dedicated spa room and an outdoor relaxation area. Immerse yourself in a personalized wellness experience with exclusive access to our top-tier spa facilities, including a serene garden and rejuvenating wellness programs.', 10, '11:00 AM', 'https://media.istockphoto.com/id/470330582/photo/beautiful-young-woman-at-spa-outdoor.jpg?s=612x612&w=0&k=20&c=fO80Rm0HO1TXi6-Xn7XK5NoK00nIDUv_yDGILs2ha7c=', 'https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1200,h_630/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/xdpqtxytsdlyctjzlrx9/Mud%20Bath%20at%20Galina%20Hotel%20and%20Spa%20.jpg', 'https://www.prensalibre.com/wp-content/uploads/2019/09/shutterstock_125874761.jpg?quality=52&w=760&h=430&crop=1'));

            // Initialize Reviews
            // Add review initialization as needed
        };
    }
}
;