package com.keyin.IslandSerenity;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import com.keyin.Users.User;
import com.keyin.Users.UserRepository;
import com.keyin.Activities.Activity;
import com.keyin.Activities.ActivityRepository;
import com.keyin.Rooms.Room;
import com.keyin.Rooms.RoomRepository;
import com.keyin.Reviews.Review;
import com.keyin.Reviews.ReviewRepository;

@SpringBootApplication
public class IslandSerenity {

    public static void main(String[] args) {
        SpringApplication.run(IslandSerenity.class, args);
    }

    @Bean
    CommandLineRunner initDatabase(UserRepository userRepository, RoomRepository roomRepository, ActivityRepository activityRepository, ReviewRepository reviewRepository) {
        return args -> {
            // Initialize Users
            userRepository.save(new User("user1", "password1"));
            userRepository.save(new User("user2", "password2"));
            userRepository.save(new User("user3", "password3"));

            // Initialize Rooms
            roomRepository.save(new Room(101, "Beachfront Swim-Up Suite", "Oceanfront", "Suite", "1 King", 3, "Indulge in breathtaking oceanfront views from this exquisite beachfront swim-up suite. Revel in the luxury of a private balcony, an elegant separate shower, a sumptuous king bed, and a plush sofa, all designed to enhance your coastal escape.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-oceanfront-junior-suite-swim-up-king-room.jpg/a960c533ec670132e78d2f3c022f1a43", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-oceanfront-junior-suite-swim-up-king-view-1.jpg/9751fde1af8bd8e515051a97e74e1b07", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-junior-suite-swim-up-king-bathroom-1.jpg/8026a666ecf7e95843ee98d52a688c8d"));
            roomRepository.save(new Room(102, "Oceanfront Terrace Family Suite", "Oceanfront", "Suite", "1 King, 2 Twins, 1 Sofa Bed", 6, "The Oceanfront Terrace Suite is on ground level, emerging from your spacious suite you will be directly on the beach which for children eager to participate in our many water activities will be a huge bonus! The master bedroom boasts a king-size bed and the second bedroom has twin beds. Outdoor living is also provided for with a terrace, day beds and dining area for the family to get together and still never miss a moment of glorious sunshine.", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Terrace-Suite-Living-Area.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Terrace.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Terrace-View.jpg"));
            roomRepository.save(new Room(103, "Tropical Garden Swim-Up Suite w/ Jacuzzi", "Tropical Garden", "Suite", "1 King", 3, "Our luxurious ground-floor Garden Swim-Up King Suite is designed to provide an unparalleled experience. It is equipped with a sumptuous king-size bed and features an indoor jacuzzi for ultimate relaxation. Additionally, guests can enjoy the privacy of a secluded garden with direct access to the pool, creating a perfect blend of comfort and convenience.", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-one-bedroom-suite-jacuzzi/elegelegance-club-one-bedroom-suite-jacuzzi1-majestic-elegance-punta-cana.jpg", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-one-bedroom-suite-jacuzzi/elegelegance-club-one-bedroom-suite-jacuzzi4-majestic-elegance-punta-cana.jpg", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-one-bedroom-suite-jacuzzi/elegelegance-club-one-bedroom-suite-jacuzzi3-majestic-elegance-punta-cana.jpg"));
            roomRepository.save(new Room(104, "Ocean Breeze Room", "Oceanfront", "Room", "1 King", 3, "The Oceanfront King Room offers a generously sized and elegantly appointed sitting area, providing an exquisite retreat for guests. With its spacious layout and French doors that open directly onto the beach, this room is ideal for those seeking to luxuriate in the sun or explore the lively surroundings. It combines ultimate comfort with the allure of adventure, ensuring a perfect blend of relaxation and excitement.", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-Breeze-Superior-Room1.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-Breeze-Superior-Room2.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-Breeze-Superior-Room8.jpg"));
            roomRepository.save(new Room(201, "Garden Suite w/ Private Pool", "Tropical Garden", "Suite", "1 King", 3, "Experience the ultimate in relaxation and luxury with the Garden Suite.The suite features an open, airy layout that seamlessly connects to a lush outdoor space, where you can enjoy a refreshing dip in your own private pool, and relax in a king bed. With elegant decor and serene garden views, this suite provides a tranquil retreat for rejuvenation and peaceful escape. Ideal for couples seeking both comfort and exclusivity, the Garden Suite promises an unforgettable stay amidst natures beauty.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-one-bedroom-master-swim-up-suite-room.jpg/eae81229981f7a3230e20831ec349497", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-one-bedroom-master-swim-up-suite-view.jpg/5647754643b1512738a01469a436e6d5", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-one-bedroom-master-swim-up-suite-bathroom-1.jpg/0948733f8eddecb10e2da060c8e4e0d0"));
            roomRepository.save(new Room(202, "Seaside Serenity Room", "Ocean", "Room", "1 King", 2, "The Ocean View King Room is a chic, open-concept studio that showcases panoramic ocean vistas through expansive windows. Designed for both relaxation and luxury, this room serves as the perfect vantage point to enjoy breathtaking sunsets. Its elegant layout and stunning views create an idyllic setting for a memorable escape, making it an ideal choice for those seeking both comfort and natural beauty.", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-View-Superior-Room.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-View-Superior-Room5.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Ocean-View-Superior-Room3.jpg"));
            roomRepository.save(new Room(203, " Tranquility Queen Suite w/ Balcony", "Ocean", "Suite", "2 Queens", 4, "The Ocean View Two Queen Suite offers a serene retreat with stunning ocean views from its private balcony. This suite features two plush queen beds, a separate shower for added convenience, and a comfortable sofa, creating a perfect blend of style and comfort for a relaxing stay.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-club-ocean-view-junior-suite-double-room.jpg/bb86c7a77baafb6ec685465c3df7f1ad", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-junior-suite-partial-view-balcony-web.jpg/900b979b507c1107eae66ba0ab075009", "https://resolve.sandals.com/sri?set=key[resolve.pixelRatio],value[1.25]&set=key[resolve.width],value[1500]&set=key[resolve.height],value[10000]&set=key[resolve.imageFit],value[containerwidth]&set=key[resolve.allowImageUpscaling],value[0]&set=key[resolve.format],value[webp]&set=fileName[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fslu%2Faccommodations%2Flarge%2Fslu-120.jpg]&source=continueonerror[true],name[image],url[global.fileName]&set=prdImageFound[global.source.success]&source=if[(!%20global.source.success)],name[base1],url[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fglobal%2Fcoming-soon%2Fbackground.jpg]&scale=options[limit],size[1500x10000]&sink=format[webp],if[(%20prdImageFound%20)],quality[70]"));
            roomRepository.save(new Room(204, "Enchanted Secret Garden Room", "Tropical Garden", "Room", "1 King", 3, "The Garden View King Room is a cozy, inviting space designed for comfort and relaxation. Featuring a plush king bed and a tranquil garden view, this room offers a peaceful retreat perfect for unwinding and enjoying the natural beauty that surrounds you.", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/375053570.jpg?k=1d9ac0f89adabec9734e56462f223268df764c1b709bda1221efb94f6938b8d8&o=&hp=1", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/375053578.jpg?k=90a1b02b15e57c739378306365b1fddbeec7d01d059000f9292d6b92dd08d6fc&o=&hp=1", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/375053548.jpg?k=05f8c8d0151c964a4edab63fa13d219f1e49181de26062279d7c1349ac8e8bdc&o=&hp=1"));
            roomRepository.save(new Room(301, "Horizon Haven Suite w/ Balcony", "Ocean", "Suite", "1 King, 2 Twins, 1 Sofa Bed", 6, "Located on the family-dedicated area of the resort, the upper level Ocean View Family Suite has the advantage of two separate bedrooms and a balcony off the master bedroom with beach views. Comfort and style are reflected in the bright, tasteful décor and furnishings and all the extra touches you would expect are included. You can be assured that your family will be thrilled with their stay here.", "https://www.majestic-resorts.com/en/dms/multiHotel-MajesticResorts/majesticElegance/rooms/new/elegance-club-junior-suite-jacuzzi/elegance-club-junior-suite-jacuzzi1-majestic-elegance-punta-cana.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/CB_Bay_Suite_2_1.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Beach-Balcony-Twin-Room.jpg"));
            roomRepository.save(new Room(302, "Serenity Suite w/ Terrace", "Ocean", "Suite", "2 King, 2 Twins, 1 Sofa Bed", 8, "The Serenity Suite is the ultimate choice for resort accommodation. Spacious, sun-filled and magnificently appointed it is ideal for sharing with other couples or for small family groups. The oceanfront terraces are large with uninterrupted views which are all your own. They have two king-size bedded rooms and one twin bedded room, all ensuite. It also features a large sitting room area extending onto the L-shaped terrace giving you those uninterrupted views in every direction.", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Carlisle-Suite.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/Carlisle-Suite-Bathroom.jpg", "https://static.arocdn.com/Sites/50/carlisle_bay/uploads/images/rooms46/roomimagethumb34/CB_Beach_Balcony_Suite_-_Balcony.JPG"));
            roomRepository.save(new Room(303, "Honeymoon Bliss Suite w/ Balcony", "Ocean", "Suite", "1 California King", 3, "The Ocean View California King Honeymoon Suite is a luxurious sanctuary offering unparalleled elegance and comfort. Featuring expansive ocean views from every window, this suite includes a grand california king-sized bed, a lavish living area, and a sophisticated dining space. The suite also boasts a private balcony, perfect for enjoying breathtaking sunsets, and a sumptuous bathroom with premium amenities. With its refined décor and spacious layout, this suite ensures a truly opulent experience.", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-presidential-suite-room-web1.jpg/47c35ae690c8524db91fc3ce7fe01c3e", "https://playa-cms-assets.s3.amazonaws.com/styled/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-presidential-suite-living-dining-room-butler-web1.jpg/783e7fe4318700164b11dd026d2a323b", "https://resolve.sandals.com/sri?set=key[resolve.pixelRatio],value[1.25]&set=key[resolve.width],value[1500]&set=key[resolve.height],value[10000]&set=key[resolve.imageFit],value[containerwidth]&set=key[resolve.allowImageUpscaling],value[0]&set=key[resolve.format],value[webp]&set=fileName[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fslu%2Faccommodations%2Flarge%2Fslu-045.jpg]&source=continueonerror[true],name[image],url[global.fileName]&set=prdImageFound[global.source.success]&source=if[(!%20global.source.success)],name[base1],url[https%3A%2F%2Fcdn.sandals.com%2Fsandals%2Fv13%2Fimages%2FEN%2Fresorts%2Fglobal%2Fcoming-soon%2Fbackground.jpg]&scale=options[limit],size[1500x10000]&sink=format[webp],if[(%20prdImageFound%20)],quality[70]"));
            roomRepository.save(new Room(401, "Skyline Luxe Penthouse Suite w/ Hot Tub & Balcony", "Ocean", "Suite", "1 California King, 2 Queens, 1 sofa bed", 8, "The Ocean View California King Penthouse Suite is a spacious, private apartment-style suite with separate living space, perfect for families or groups. Located on the top floor and accommodates up to 8 guests with 2 bedrooms, 3 full bathrooms, and a sleeping arrangement that includes a california king-sized bed, two queen-sized beds, and a full sofa bed. Enjoy a covered balcony with a private hot tub.", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Playitas-Suite.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Playitas-Suite18.jpg", "https://www.arenasdelmar.com/wp-content/uploads/2024/05/ADM_Playitas-Suite6.jpg"));
            roomRepository.save(new Room(1, "Rainforest Retreat Villa", "Rainforest", "Villa", "1 California King", 3, "Embrace the essence of island paradise in the Rainforest Suite, where the vibrant rainforest and tranquil ocean come together. This luxurious suite features an open-plan design that seamlessly blends with the lush tropical surroundings, creating a serene and inviting atmosphere. Guests will enjoy a restful night in a plush king-size bed, waking to the soothing sounds of the ocean, mixed with the unique soundtrack of the rainforest and breathtaking views of the island. The suite's gentle blend of forest fragrances and ocean breezes promises to rejuvenate both body and mind, offering an unparalleled tropical escape for two adults.", "https://www.greengetaways.com.au/wp-content/uploads/2017/12/Crystal-Creek-lodges_cedar_wide_evening.jpg", "https://www.greengetaways.com.au/wp-content/uploads/2017/12/Crystal-Creek-deck_wide.jpg", "https://www.greengetaways.com.au/wp-content/uploads/2017/12/Crystal-Creek-lodges_numinbah_bed_bath_view.jpg"));
            roomRepository.save(new Room(2, "Ocean Top Villa", "Oceanfront", "Villa", "1 California King", 3, "Elevate your escape with the Ocean Top Villa, a premier retreat perched above the azure waves. This exquisite villa offers uninterrupted ocean views and the ultimate in luxury with a private infinity pool and an indulgent jacuzzi. The open-plan design seamlessly integrates indoor and outdoor spaces, allowing you to fully immerse yourself in the stunning seascape. Relax on your private terrace, take a dip in the infinity pool, or unwind in the jacuzzi while gazing out over the horizon.", "https://cache.marriott.com/is/image/marriotts7prod/mlera-bedroom-ocean-1150:Wide-Hor?wid=1336&fit=constrain", "https://cache.marriott.com/content/dam/marriott-renditions/MLERA/mlera-ocean-villa-3568-hor-wide.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=1336px:*", "https://cache.marriott.com/content/dam/marriott-renditions/MLERA/mlera-villa-bathroom-3557-hor-wide.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=1336px:*"));
            roomRepository.save(new Room(3, "Beachfront Villa w/ Private Beach & Pool", "Beachfront", "Villa", "1 King", 3, "Indulge in the ultimate coastal luxury with the Beachfront Villa, where your private paradise awaits. This exceptional villa offers exclusive access to a pristine private beach and a stunning pool, seamlessly blending the beauty of the shoreline with sophisticated comfort. Step directly from your villa onto soft, sandy shores, or relax in your private pool while soaking in panoramic ocean views. Designed for the discerning traveler, the Beachfront Villa provides an unparalleled setting for relaxation and indulgence, making every moment of your stay a serene and memorable experience.", "https://worldvillas.eu/img/641x336/8492.jpg", "https://worldvillas.eu/img/641x336/8492/7defd00746891b554c6f4be2907467f4.jpg", "https://worldvillas.eu/img/641x336/8492/491398f7c06408285de09cf7d9c8f29f.jpg"));
            roomRepository.save(new Room(4, "Family Beachfront Villa w/ Pool", "Beachfront", "Villa", "1 Queen, 2 Twin, 1 Daybed", 5, "Create unforgettable memories with your loved ones in the Family Beachfront Villa. This spacious and inviting villa offers direct access to a beautiful sandy beach, perfect for family fun and relaxation. Enjoy quality time together in the large, private pool or explore the nearby shoreline. Designed with comfort and convenience in mind, the villa features ample living space, modern amenities, and stunning ocean views, ensuring a memorable and enjoyable stay for families of all sizes. The Family Beachfront Villa is your ideal coastal retreat for bonding and making the most of every sun-drenched day.", "https://maldives-magazine.com/pictures/constance-halaveli-family-beach-pool-villa.jpg", "https://maldives-magazine.com/pictures/constance-halaveli-family-beach-pool-villa-bedroom.jpg", "https://maldives-magazine.com/pictures/constance-halaveli-family-beach-pool-villa-bedroom-5.jpg"));
            roomRepository.save(new Room(5, "Sky Nest Treehouse", "Rainforest", "Villa", "2 King, 2 Twin, 1 Sofa Bed", 8, "Experience luxury tree-top living in this 4,000 square-foot villa nestled in the rainforest. Combining eco-friendly design with striking architecture, the villa features contemporary interiors, a sleek kitchen with a marble island, and a beautiful stone hot tub. Upstairs, 3 bedrooms offer ensuite bathrooms, luxury linens, flat-screen TVs, and Mexican-inspired decor, all opening to a wrap-around terrace for al fresco lounging. With access to nearby beach clubs, hiking and biking trails, and included amenities like daily housekeeping and 24/7 security, this villa promises an unforgettable tropical retreat.", "https://gallery.streamlinevrs.com/units-gallery/00/05/4F/image_164231367.jpeg", "https://gallery.streamlinevrs.com/units-gallery/00/05/4F/image_164231384.jpeg", "https://gallery.streamlinevrs.com/units-gallery/00/05/4F/image_164231379.jpeg"));


            // Initialize Activities
            // Add activity initialization as needed

            // Initialize Reviews
            // Add review initialization as needed
        };
    }
}
